### ISSUE TITLE
Install prerequisites required

### ISSUE THREAD

**Issue by frissner** [kenlog/EncryptedContent#2]
Hi,
I installed kanboard on an internal server without ssl or something.
kanboard is provided by a proxy which ensures ssl (https)
when clicking on "Encrypted content" kanboard say "This feature requires the use of an SSL certificate on the server"
how do i have to configure ssl so that the plugin works?
is it sufficient to configure https on the server hosting kanboard?

Best,
Florian

**Comment by kenlog** [comment]
Hi @frissner yes is sufficient to install an SSL certificate, also self-signed, to allow it to work

**Comment by nickcowans** [comment]
Hi - I wasn't able to get this to work using a docker instance where https is deal with with an nginx reverse proxy on host machine, it still says "This feature requires the use of an SSL certificate on the server". If I want to install my own self-signed certificate in the docker container please can you advise where should they be saved?
